language: python
dist: xenial
python:
- '3.6'
- '3.7'
- 3.8-dev
install:
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
script:
  - travis_wait pytest --cov=pyms tests/
after_success:
  - coveralls
deploy:
  provider: pypi
  user: DomDF
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: c8kiGOCPwUvcXtgyY++1cRqhzxc0HGRolbiHRNZO9N8oOxX79poRvwbI/D0eW94xXWGF9V9MoKhalDvxq/jQ/AU7YMg0qnaQhleBkxSJGvEC3QSxUpiG4JOtuxJIdFXGEuH2chwqY9YLK2XyBT7NFkz8qXBvB3FVb42H7d3SCE5FWURETnq4srJknblEwNKepQeKcRrN4cyrBRbMQrn3nzdU5L0XdaO+Cy9GbCV+vhJyMuUI0YYxnpPZz6/y7X5lqSzxzkXIwaxQAazhQFSKB5vEmR0BF3DZmYl62TDNY6hUtjvrfn0mWQEIXqG8iU7g0wU/XvpqLfyO4+y3604d50gEx3G0y5wpVG7iyllsos6iLKX4spomo1qQGoEkE/Sp8EeNGP3y/iBg3uBEq54CYG5wR9QYUWqOhuh9lziJRhUpq+t1P0FOfkM8cSXGvdr9tCjStrDeac2syLKindVZy1Juc5grdJi5q686SCT7Ts46wRR4YWDxurjzDWyIvMpnRI7OXuEziPgLmeT7jRPNP3TKWcGQNuDFQ1SlPDBgaGIRO85AGpTwImXiRQMlO95emhvCVwvG+3rAvXuRpPkrJvx2XL8trDIPXqGcXkXohw/2n7jbZ4HjCUNNgZZxkyokgVbp5UL1M861KhWjIrylis4ReTt+t66Ab8kB9vSNESM=
