version: 1.0.{build}
clone_depth: 50  # The same depth Travis has
image: Visual Studio 2019

environment:
  matrix:
    # Python36
    - TOXENV: "py36"
      PYTHON: "C:\\Python36"
      TOX_APPVEYOR_X64: 0
    # Python37
    - TOXENV: "py37"
      PYTHON: "C:\\Python37"
      TOX_APPVEYOR_X64: 0
    # Python38
    - TOXENV: "py38"
      PYTHON: "C:\\Python38"
      TOX_APPVEYOR_X64: 0
    # Python36-x64
    - TOXENV: "py36"
      PYTHON: "C:\\Python36-x64"
      TOX_APPVEYOR_X64: 1
    # Python37-x64
    - TOXENV: "py37"
      PYTHON: "C:\\Python37-x64"
      TOX_APPVEYOR_X64: 1
    # Python38-x64
    - TOXENV: "py38"
      PYTHON: "C:\\Python38-x64"
      TOX_APPVEYOR_X64: 1

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel Cython tox tox-appveyor"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"
